services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: camagru_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - uploads_volume:/var/www/html/public/uploads
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - camagru

  # PHP service
  php:
    build:
      context: ./docker/php
    container_name: camagru_php
    volumes:
      - ./:/var/www/html
      - uploads_volume:/var/www/html/public/uploads
    depends_on:
      - mariadb
    networks:
      - camagru
    env_file:
      - .env

  # MySQL service
  mariadb:
    image: yobasystems/alpine-mariadb:11.4.5
    container_name: camagru_mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - camagru

  # MailHog service
  mailhog:
    image: mailhog/mailhog
    container_name: camagru_mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
    networks:
      - camagru

# Networks
networks:
  camagru:
    driver: bridge

# Volumes
volumes:
  uploads_volume:  # Add this new volume
    driver: local
  mariadb_data:
    driver: local