services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: camagru_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - camagru

  # PHP service
  php:
    build:
      context: ./docker/php
    container_name: camagru_php
    volumes:
      - ./:/var/www/html
      - vendor_volume:/var/www/html/vendor
    depends_on:
      - mysql
    networks:
      - camagru
    env_file:
      - .env

  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: camagru_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - camagru

  # MailHog service
  mailhog:
    image: mailhog/mailhog
    container_name: camagru_mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
    networks:
      - camagru

# Networks
networks:
  camagru:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
  vendor_volume:
    driver: local